### ISSUE TITLE
No definition of each variable type?

### ISSUE THREAD

**Issue by HSeo** [MicrosoftDocs/cpp-docs.ja-jp#227]
Is it possible to omit the definition of each variable type in bit_fields2.cpp, such as
unsigned nWeekDay  : 3;    // 0..7   (3 bits)
instead of 
unsigned int nWeekDay  : 3;    // 0..7   (3 bits)
?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a78c89c2-7d34-fac8-9043-4099bc8637dd
* Version Independent ID: e265dccc-e3f6-7464-a6cf-e0e19aea772f
* Content: [C++ ビット フィールド](https://docs.microsoft.com/ja-jp/cpp/cpp/cpp-bit-fields?view=vs-2019#feedback)
* Content Source: [docs/cpp/cpp-bit-fields.md](https://github.com/MicrosoftDocs/cpp-docs.ja-jp/blob/live/docs/cpp/cpp-bit-fields.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by srvbpigh** [comment]
Hello, @HSeo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #2041](https://github.com/MicrosoftDocs/cpp-docs/issues/2041) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @HSeo, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/2041. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
